// <auto-generated />
namespace ngay8thang3_Complete.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_objKhuyenMai : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_objKhuyenMai));
        
        string IMigrationMetadata.Id
        {
            get { return "202304301737166_add_objKhuyenMai"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
